### ISSUE TITLE
E: unable to locate package libpcl-1.7-all-dev

### ISSUE THREAD

**Issue by csush** [yzrobot/cloud_annotation_tool#10]
Hi, pretty new to all this. My OS is Ubuntu 18.04.2 Bionic Beaver. I get the following error when running `sudo apt-get install libpcl-1.7-all-dev` :
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libpcl-1.7-all-dev
E: Couldn't find any package by glob 'libpcl-1.7-all-dev'
E: Couldn't find any package by regex 'libpcl-1.7-all-dev'`

Any help? Thanks

**Comment by pixx1** [comment]
Hi man!
I have some news for you. For me following fixed the issue:
`sudo apt install libpcl-dev`

If you run make and have following error:
> make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by 'cloud_annotation_tool'.  Stop.

You need to install this package:
`sudo apt-get install libproj-dev`

Just in case ;-)

All the best
pix_1

**Comment by CaffeMrDe** [comment]
The following additional packages will be installed:
  libvtk6-dev libvtk6-qt-dev
Suggested packages:
  libpcl-doc vtk6-doc vtk6-examples
The following packages will be REMOVED:
  libvtk5-dev
The following NEW packages will be installed:
  libpcl-dev libvtk6-dev libvtk6-qt-dev


I do the action : sudo apt-get install libvtk5-dev . It get me this. How do I deal with it ?

**Comment by pixx1** [comment]
Hi CaffeMrDe.
For me it is working with libvtk6. I have following libvtk packages installed:

> libvtk6-dev
> libvtk6-qt-dev
> libvtk6.2
> libvtk6.2-qt
> libvtk6-java

I'm not sure if i need all of them, I tested a few other things.

All the best
pix_1

**Comment by CaffeMrDe** [comment]
```
`/usr/bin/ld: cannot find -lvtkRendering
/usr/bin/ld: cannot find -lvtkGraphics
/usr/bin/ld: cannot find -lvtkHybrid
/usr/bin/ld: cannot find -lQVTK
/usr/bin/ld: cannot find -lvtkRendering
/usr/bin/ld: cannot find -lvtkGraphics
/usr/bin/ld: cannot find -lvtkHybrid
/usr/bin/ld: cannot find -lQVTK
collect2: error: ld returned 1 exit status
CMakeFiles/cloud_annotation_tool.dir/build.make:459: recipe for target 'cloud_annotation_tool' failed
make[2]: *** [cloud_annotation_tool] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cloud_annotation_tool.dir/all' failed
make[1]: *** [CMakeFiles/cloud_annotation_tool.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I met the question about it .Why? THis is very difficlut to install it....

**Comment by cuge1995** [comment]
the answer is
```shell
sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl  
sudo apt-get update  
sudo apt-get install libpcl-1.7-all-dev
```
