### ISSUE TITLE
Problem compiling on Ubuntu 16.04

### ISSUE THREAD

**Issue by Gitanjali450** [yzrobot/cloud_annotation_tool#13]
Hello,

I am trying to compile the tool on Ubuntu 16.04, but when I run the following command:

sudo apt-get install libpcl-1.7-all-dev

I get the following error:

E: Unable to locate package libpcl-1.7-all-dev

Is there any substitute command for installing pcl 1.7 all?
If I use the following command:

sudo apt-get install libpcl1

then, after cmake .. it gives the following error:

CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PCL" (requested
  version 1.2) with any of the following names:

    PCLConfig.cmake
    pcl-config.cmake

Any help would be appreciated. Thank you.

**Comment by zjbaby** [comment]
sudo apt-get install libpcl-dev
