### ISSUE TITLE
Error with make

### ISSUE THREAD

**Issue by Gitanjali450** [yzrobot/cloud_annotation_tool#14]
When I run the 'make' command, I get the following error:

/usr/bin/ld: cannot find -lvtkRendering
/usr/bin/ld: cannot find -lvtkGraphics
/usr/bin/ld: cannot find -lvtkHybrid
/usr/bin/ld: cannot find -lQVTK
/usr/bin/ld: cannot find -lvtkRendering
/usr/bin/ld: cannot find -lvtkGraphics
/usr/bin/ld: cannot find -lvtkHybrid
/usr/bin/ld: cannot find -lQVTK

Could you please help?

**Comment by parisChatz** [comment]
Assuming you have installed every dependency correctly, delete the `CMakeLists.txt` and change the `CMakeLists_Xenial.txt` to `CMakeLists.txt`.
