### ISSUE TITLE
Installing the packages VTK and pcl conflict with each other...

### ISSUE THREAD

**Issue by nesakeerthi** [yzrobot/cloud_annotation_tool#19]
@yzrobot 

VTK 5.x: sudo apt-get install libvtk5-dev 
when i tried to install the above package its shwoing to remove the follwoing.

The following packages will be REMOVED:
  libpcl-dev libvtk6-dev libvtk6-qt-dev ros-kinetic-camera-calibration ros-kinetic-compressed-depth-image-transport ros-kinetic-compressed-image-transport ros-kinetic-cv-bridge
  ros-kinetic-depth-image-proc ros-kinetic-desktop ros-kinetic-desktop-full ros-kinetic-gazebo-plugins ros-kinetic-gazebo-ros-pkgs ros-kinetic-image-geometry ros-kinetic-image-pipeline
  ros-kinetic-image-proc ros-kinetic-image-publisher ros-kinetic-image-rotate ros-kinetic-image-transport-plugins ros-kinetic-image-view ros-kinetic-opencv3 ros-kinetic-pcl-conversions
  ros-kinetic-pcl-ros ros-kinetic-perception ros-kinetic-perception-pcl ros-kinetic-rqt-common-plugins ros-kinetic-rqt-image-view ros-kinetic-simulators ros-kinetic-stereo-image-proc
  ros-kinetic-theora-image-transport ros-kinetic-vision-opencv ros-kinetic-viz
The following NEW packages will be installed:
  libvtk5-dev

did the cmake with following warning

- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- Eigen found (include: /usr/include/eigen3, version: 3.2.92)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   iostreams
--   serialization
--   regex
-- QHULL found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libqhull.so;debug;/usr/lib/x86_64-linux-gnu/libqhull.so)
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
-- looking for PCL_COMMON
-- looking for PCL_KDTREE
-- looking for PCL_OCTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_SURFACE
-- looking for PCL_2D
-- looking for PCL_FEATURES
-- looking for PCL_IO
-- looking for PCL_GEOMETRY
-- looking for PCL_ML
-- looking for PCL_SEGMENTATION
-- looking for PCL_REGISTRATION
-- looking for PCL_KEYPOINTS
-- looking for PCL_TRACKING
-- looking for PCL_RECOGNITION
-- looking for PCL_STEREO
-- Configuring done
-- Generating done

please help with this issu

**Comment by luorui93** [comment]
You should replace the CMakelist.txt with CMakelist_Xenial.txt (in the same folder) and try to build again. I believe the prior one is for Ubuntu 14.04
